# Generated by Django 3.1.7 on 2021-03-28 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Whiteboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem_domain', models.TextField()),
                ('edge_cases', models.CharField(max_length=200)),
                ('visual', models.ImageField(upload_to='images/')),
                ('algorithm', models.TextField()),
                ('big_o', models.CharField(max_length=200)),
                ('pseudo_code', models.TextField()),
                ('code', models.TextField()),
                ('verification', models.TextField()),
                ('structure', models.CharField(choices=[('Arr', 'Array'), ('Stack', 'Stack'), ('Queue', 'Queue'), ('LL', 'Linked List'), ('BT', 'Binary Tree'), ('BST', 'Binary Search Tree'), ('HT', 'Hash Table'), ('IS', 'Insertion Sort'), ('MS', 'Merge Sort'), ('QS', 'Quick Sort')], default='Arr', max_length=20)),
                ('action', models.CharField(choices=[('Sum', 'Find the sum of all elements'), ('Value', 'If the value is present, return True'), ('FD', 'Return a list of duplicate values'), ('RD', 'Remove all duplicate values'), ('RV', 'Reverse the values'), ('Max', 'Find the max value'), ('Min', 'Find the min value'), ('Sort', 'Sort the values'), ('Imp', 'Implement data structure'), ('Def', 'Define the general algorithm in your own words')], default='Def', max_length=64)),
                ('method', models.CharField(choices=[('REC', 'Recursive'), ('IT', 'Iterative'), ('NA', 'Not Applicable')], default='NA', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
